### ISSUE TITLE
Parts of setup.sh no longer necessary?

### ISSUE THREAD

**Issue by zilexa** [vstoppe/mycloud#1]
Hi, I have been using FileRun, as it is faster and more lightweight than Nextcloud (and purely focused on file management, no other frills). But I am eager to try out Nextcloud-fpm with postgresql db and redis, now that they have a new rust engine (nextcloud:21).

I am copying your 05 version line by line. The setup.sh however contains a for loop that doesn't make sense as it doesn't seem to test anything?

```
for srv in config custom_apps data themes;do
	mkdir -p    $DATA/$SERVICE/$srv
	chown -R 82 $DATA/$SERVICE/$srv
done
```
What is "srv" and all those other names? I don't understan what they are referring to (config, custom_apps, data, themes) as those folders don't exist (yet?). 
Or is this script no longer necessary? I did create the mysq folder and subfolders myself.

**Comment by vstoppe** [comment]
Ah, maybe I should  delete this script. I think I used it when switching from Apache as a frontend to nginx/fpm. During the switch you need to change the permissions of the nextcloud files to the preferred value of the web server. But this should not be necessary while setting up the container stack.
I just hope my docker-compose files can help some nerds in the wild.. :-)
Edit:
I just check the setup process. Yes some things need to be done. I wil update the script and documentation.

**Comment by vstoppe** [comment]
Hi Zilexa! Today I completely reworked the setup Script. I removed the old setup.sh and replaced it by a much more sophisticated nc-setup.sh. I also updated my Readme.md.
I have some further Ideas of how to improve the docker-compose files. Hope I find the time.. :-)
Thanks for your input!
